# Generated by Django 5.0.6 on 2024-06-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_productsmodels_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodels',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModels',
        ),
        migrations.DeleteModel(
            name='ProductsModels',
        ),
    ]
