# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='products-image/'),
        ),
    ]
