# Generated by Django 5.0.6 on 2024-05-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsmodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModels',
            new_name='AuthorProducstModels',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='dinemison',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='referensec',
        ),
    ]
