# Generated by Django 5.0.6 on 2024-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorymodels_productsmodels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodels',
            name='image2',
            field=models.ImageField(null=True, upload_to='products-image/'),
        ),
        migrations.AddField(
            model_name='productsmodels',
            name='image3',
            field=models.ImageField(null=True, upload_to='products-image/'),
        ),
        migrations.AddField(
            model_name='productsmodels',
            name='image4',
            field=models.ImageField(null=True, upload_to='products-image/'),
        ),
        migrations.AddField(
            model_name='productsmodels',
            name='image5',
            field=models.ImageField(null=True, upload_to='products-image/'),
        ),
    ]
